springbootDependenciesVersion=boot-4.1.1-1

# Re-exported platforms
springBootVersion=4.1.1
springCloudVersion=2025.1.3
springCloudAlibabaVersion=2025.1.0.0
querydslVersion=5.1.0

# Third-party constraints
mapstructVersion=1.6.3
lombokMapstructBindingVersion=0.2.0
knife4jVersion=5.0.13
alibabaNacosConfigVersion=2025.1.0.0
jjwtVersion=0.12.6
commonsConfiguration2Version=2.15.1
commonsBeanutilsVersion=1.11.0
commonsPool2Version=2.13.1
casbinSpringBootStarterVersion=2.0.0
jcasbinRedisWatcherVersion=1.9.0
guavaVersion=33.6.0-jre
caffeineVersion=3.2.4
springbootUtilsVersion=0.0.1
